/** 
 * 调用本地api的action type的常量，以及几个调用状态常量
 */
export const CALL_API_LOCAL = "Call_API_LOCAL"
export const CALL_API_LOCAL_START = "CALL_API_LOCAL_START"
export const CALL_API_LOCAL_FAIL = "CALL_API_LOCAL_FAIL"

/** 
 * 本地下载action type的常量，以及几个下载状态常量
 */
export const DOWNLOAD = "CALL_API_LOCAL_DOWNLOAD"
export const DOWNLOAD_WAIT = "CALL_API_LOCAL_DOWNLOAD_WAIT"
export const DOWNLOAD_START = "CALL_API_LOCAL_DOWNLOAD_START"
export const DOWNLOAD_FAIL = "CALL_API_LOCAL_DOWNLOAD_FAIL"
export const DOWNLOAD_PROGRESS = "CALL_API_LOCAL_DOWNLOAD_PROGRESS"
export const DOWNLOAD_SUCCESS = "CALL_API_LOCAL_DOWNLOAD_SUCCESS"
export const DOWNLOAD_PAUSE = "CALL_API_LOCAL_DOWNLOAD_PAUSE"

/** 
 * 本地上传action type的常量，以及几个上传状态常量
 */
export const UPLOAD = "CALL_API_LOCAL_UPLOAD"
export const UPLOAD_WAIT = "CALL_API_LOCAL_UPLOAD_WAIT"
export const UPLOAD_START = "CALL_API_LOCAL_UPLOAD_START"
export const UPLOAD_FAIL = "CALL_API_LOCAL_UPLOAD_FAIL"
export const UPLOAD_PROGRESS = "CALL_API_LOCAL_UPLOAD_PROGRESS"
export const UPLOAD_SUCCESS = "CALL_API_LOCAL_UPLOAD_SUCCESS"
export const UPLOAD_PAUSE = "CALL_API_LOCAL_UPLOAD_PAUSE"